version: '3.8'

services:
  app:
    build: .
    image: flashscore-scraping
    container_name: flashscore-scraping
    shm_size: '256m'
    volumes:
      - ./src/csv:/app/src/csv
      - ./logs:/app/logs
